apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vault
  namespace: security
  labels:
    app.kubernetes.io/name: vault
    homelab/stack: security
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - secrets.in.alybadawy.com
      secretName: vault-secrets-tls
  rules:
    - host: secrets.in.alybadawy.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vault
                port:
                  number: 8200
