apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault-data-nas
  labels:
    app.kubernetes.io/name: vault
    homelab/stack: security
spec:
  capacity:
    storage: 5Gi
  accessModes: [ReadWriteOnce]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - nfsvers=3
  nfs:
    server: 172.20.20.2
    path: /var/nfs/shared/storage/vault-data
