apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-data
  namespace: security
  labels:
    app.kubernetes.io/name: vault
    homelab/stack: security
  annotations:
    recurring-job-group.longhorn.io/default: enabled
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
