apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage-secrets
  namespace: websites
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: k8s-secrets
    kind: ClusterSecretStore
  target:
    name: homepage-secrets
    creationPolicy: Owner
  data:
    - secretKey: grafana-password
      remoteRef:
        key: grafana-admin
        property: admin-password
    - secretKey: argocd-token
      remoteRef:
        key: homepage
        property: argocd-token
    - secretKey: immich-token
      remoteRef:
        key: homepage
        property: immich-token
    - secretKey: nextcloud-user
      remoteRef:
        key: homepage
        property: nextcloud-user
    - secretKey: nextcloud-password
      remoteRef:
        key: homepage
        property: nextcloud-password
    - secretKey: authentik-token
      remoteRef:
        key: homepage
        property: authentik-token
