apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-config
  namespace: auth
  labels:
    app.kubernetes.io/name: authentik
    homelab/stack: auth
data:
  AUTHENTIK_POSTGRESQL__HOST: postgres.db.svc.cluster.local
  AUTHENTIK_POSTGRESQL__PORT: "5432"
  AUTHENTIK_POSTGRESQL__NAME: authentik
  AUTHENTIK_REDIS__HOST: redis.db.svc.cluster.local
  AUTHENTIK_REDIS__PORT: "6379"
  AUTHENTIK_ERROR_REPORTING__ENABLED: "false"
