apiVersion: v1
kind: PersistentVolume
metadata:
  name: authentik-media-nas
  labels:
    app.kubernetes.io/name: authentik
    homelab/stack: auth
spec:
  capacity:
    storage: 1Gi
  accessModes: [ReadWriteOnce]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - nfsvers=3
  nfs:
    server: 172.20.20.2
    path: /var/nfs/shared/storage/authentik-media
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: authentik-templates-nas
  labels:
    app.kubernetes.io/name: authentik
    homelab/stack: auth
spec:
  capacity:
    storage: 1Gi
  accessModes: [ReadWriteOnce]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - nfsvers=3
  nfs:
    server: 172.20.20.2
    path: /var/nfs/shared/storage/authentik-templates
