apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-media
  namespace: security
  labels:
    app.kubernetes.io/name: authentik
    homelab/stack: auth
  annotations:
    recurring-job-group.longhorn.io/default: enabled
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-templates
  namespace: security
  labels:
    app.kubernetes.io/name: authentik
    homelab/stack: auth
  annotations:
    recurring-job-group.longhorn.io/default: enabled
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
