apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-media-lh
  namespace: security
  labels:
    app.kubernetes.io/name: authentik
    homelab/stack: auth
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-templates-lh
  namespace: security
  labels:
    app.kubernetes.io/name: authentik
    homelab/stack: auth
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
