apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-media
  namespace: security
  labels:
    app.kubernetes.io/name: authentik
    homelab/stack: auth
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: ""
  volumeName: authentik-media-nas
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-templates
  namespace: security
  labels:
    app.kubernetes.io/name: authentik
    homelab/stack: auth
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: ""
  volumeName: authentik-templates-nas
  resources:
    requests:
      storage: 1Gi
