apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-secret
  namespace: immich
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: k8s-secrets
    kind: ClusterSecretStore
  target:
    name: immich-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_USERNAME
      remoteRef:
        key: immich-db
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: immich-db
        property: password
