apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-data-nas
  labels:
    app.kubernetes.io/name: immich
    homelab/stack: immich
spec:
  capacity:
    storage: 750Gi
  accessModes: [ReadWriteOnce]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - nfsvers=3
  nfs:
    server: 172.20.20.2
    path: /var/nfs/shared/storage/immich-data
