apiVersion: v1
kind: Service
metadata:
  name: immich-server
  namespace: immich
  labels:
    app.kubernetes.io/name: immich-server
    homelab/stack: immich
spec:
  selector:
    app.kubernetes.io/name: immich-server
  ports:
    - port: 2283
      targetPort: 2283
