apiVersion: v1
kind: ConfigMap
metadata:
  name: ip-nginx-config
  namespace: websites
  labels:
    app.kubernetes.io/name: ip
    homelab/stack: ip
data:
  default.conf: |
    server {
        listen 80;
        location / {
            default_type application/json;
            add_header Cache-Control "no-store";
            return 200 '{"ip":"$http_x_real_ip"}';
        }
    }
