apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-secret
  namespace: cloud
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: k8s-secrets
    kind: ClusterSecretStore
  target:
    name: nextcloud-secret
    creationPolicy: Owner
  data:
    - secretKey: database_user
      remoteRef:
        key: nextcloud-db
        property: username
    - secretKey: database_password
      remoteRef:
        key: nextcloud-db
        property: password
