apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-config-nas
  labels:
    app.kubernetes.io/name: nextcloud
    homelab/stack: cloud
spec:
  capacity:
    storage: 3Gi
  accessModes: [ReadWriteOnce]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - nfsvers=3
  nfs:
    server: 172.20.20.2
    path: /var/nfs/shared/storage/nextcloud-config
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-data-nas
  labels:
    app.kubernetes.io/name: nextcloud
    homelab/stack: cloud
spec:
  capacity:
    storage: 150Gi
  accessModes: [ReadWriteOnce]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - nfsvers=3
  nfs:
    server: 172.20.20.2
    path: /var/nfs/shared/storage/nextcloud-data
