apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-config
  namespace: cloud
  labels:
    app.kubernetes.io/name: nextcloud
    homelab/stack: cloud
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: ""
  volumeName: nextcloud-config-nas
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data
  namespace: cloud
  labels:
    app.kubernetes.io/name: nextcloud
    homelab/stack: cloud
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: ""
  volumeName: nextcloud-data-nas
  resources:
    requests:
      storage: 150Gi
