apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: speedtest-secret
  namespace: speedtest
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: k8s-secrets
    kind: ClusterSecretStore
  target:
    name: speedtest-secret
    creationPolicy: Owner
  data:
    - secretKey: app-key
      remoteRef:
        key: speedtest-tracker
        property: app-key
