apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: speedtest-data
  namespace: speedtest
  labels:
    app.kubernetes.io/name: speedtest-tracker
    homelab/stack: speedtest
  annotations:
    recurring-job-group.longhorn.io/default: enabled
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn-local
  resources:
    requests:
      storage: 1Gi
