apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-in-alybadawy-com
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  secretName: wildcard-in-alybadawy-com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "*.in.alybadawy.com"
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "argocd,ingress-nginx"
