apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-webhook-vercel
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://baarde.github.io/cert-manager-webhook-vercel
    chart: cert-manager-webhook-vercel
    targetRevision: "0.5.0"
    helm:
      values: |
        groupName: acme.baarde.eu
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
