title: Homelab
theme: dark
color: slate
headerStyle: clean
allowedHosts: in.alybadawy.com
layout:
  Infrastructure:
    style: row
    columns: 4
  Monitoring:
    style: row
    columns: 3
  Applications:
    style: row
    columns: 4
