- search:
    provider: google
    target: _blank
    text_size: l
- resources:
    cpu: true
    memory: true
    disk:
      - /
      - /mnt/ssd-1tb
      - /mnt/nas/backups
    uptime: true
    refresh: 3000
