apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-data-lh
  namespace: security
  labels:
    app.kubernetes.io/name: vaultwarden
    homelab/stack: vaultwarden
  annotations:
    recurring-job-group.longhorn.io/default: enabled
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
