apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: emcomms
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    homelab/stack: nj2pc-oem
spec:
  project: default
  source:
    repoURL: https://github.com/AlyBadawy/nj2pc-oem
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: hams
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
