---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-secret
  namespace: db
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: k8s-secrets
    kind: ClusterSecretStore
  target:
    name: postgres-secret
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: postgres-secret
        property: POSTGRES_USER
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: postgres-secret
        property: POSTGRES_PASSWORD
    - secretKey: POSTGRES_DB
      remoteRef:
        key: postgres-secret
        property: POSTGRES_DB
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-db
  namespace: db
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: k8s-secrets
    kind: ClusterSecretStore
  target:
    name: authentik-db
    creationPolicy: Owner
  data:
    - secretKey: AUTHENTIK_DB_USER
      remoteRef:
        key: authentik-db
        property: username
    - secretKey: AUTHENTIK_DB_PASSWORD
      remoteRef:
        key: authentik-db
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-db
  namespace: db
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: k8s-secrets
    kind: ClusterSecretStore
  target:
    name: immich-db
    creationPolicy: Owner
  data:
    - secretKey: IMMICH_DB_USER
      remoteRef:
        key: immich-db
        property: username
    - secretKey: IMMICH_DB_PASSWORD
      remoteRef:
        key: immich-db
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-db
  namespace: db
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: k8s-secrets
    kind: ClusterSecretStore
  target:
    name: nextcloud-db
    creationPolicy: Owner
  data:
    - secretKey: NEXTCLOUD_DB_USER
      remoteRef:
        key: nextcloud-db
        property: username
    - secretKey: NEXTCLOUD_DB_PASSWORD
      remoteRef:
        key: nextcloud-db
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pgadmin-secret
  namespace: db
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: k8s-secrets
    kind: ClusterSecretStore
  target:
    name: pgadmin-secret
    creationPolicy: Owner
  data:
    - secretKey: PGADMIN_DEFAULT_EMAIL
      remoteRef:
        key: pgadmin-secret
        property: PGADMIN_DEFAULT_EMAIL
    - secretKey: PGADMIN_DEFAULT_PASSWORD
      remoteRef:
        key: pgadmin-secret
        property: PGADMIN_DEFAULT_PASSWORD
