apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pgadmin-secret
  namespace: db
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: k8s-secrets
    kind: ClusterSecretStore
  target:
    name: pgadmin-secret
    creationPolicy: Owner
  data:
    - secretKey: PGADMIN_DEFAULT_EMAIL
      remoteRef:
        key: pgadmin-secret
        property: PGADMIN_DEFAULT_EMAIL
    - secretKey: PGADMIN_DEFAULT_PASSWORD
      remoteRef:
        key: pgadmin-secret
        property: PGADMIN_DEFAULT_PASSWORD
