apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  namespace: db
  labels:
    app.kubernetes.io/name: pgadmin
    homelab/stack: db
spec:
  selector:
    app.kubernetes.io/name: pgadmin
  ports:
    - port: 80
      targetPort: 80
