apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: db
  labels:
    app.kubernetes.io/name: postgres
    homelab/stack: db
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: ""
  volumeName: postgres-data-nas
  resources:
    requests:
      storage: 7Gi
